services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - STORAGE_DRIVER=${STORAGE_DRIVER:-sqlite}
      - DB_PATH=${DB_PATH:-data/cosumutuel.db}
    ports:
      - "4000:4000"
    volumes:
      - ./backend/data:/usr/src/app/data
      - ./backend/uploads:/usr/src/app/uploads
      - ./backend/bordereaux:/usr/src/app/bordereaux
      - ./backend/documents.json:/usr/src/app/documents.json
      - ./backend/history.json:/usr/src/app/history.json
      - ./backend/templates:/usr/src/app/templates
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
    ports:
      - "5173:80"   # http://localhost:5173
    depends_on:
      - backend     # ordre de démarrage simple
    restart: unless-stopped
